version: '3.7'
services:
  telegraf:
    image: telegraf
    hostname: tick_telegraf
    configs:
    - source: telegraf-conf
      target: /etc/telegraf/telegraf.conf
    ports:
    - 8186:8186
    - 8092:8092
    - 8094:8094/udp
  influxdb:
    image: influxdb
    hostname: tick_influx
    configs:
    - source: influx-conf
      target: /etc/influxdb/influxdb.conf
    volumes:
      - influx_volume:/var/lib/influxdb
  chronograf:
    image: chronograf
    hostname: tick_chronograf
    ports:
    - 8888:8888
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]
    volumes:
      - chrono_volume:/var/lib/chronograf
  kapacitor:
    image: kapacitor
    hostname: tick_kapacitor
    environment:
    - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

configs:
  telegraf-conf:
    file: ./telegraf.conf
  influx-conf:
    file: ./influxdb.conf

volumes:
  influx_volume:    
  chrono_volume:
